### ISSUE TITLE
Support own types

### ISSUE THREAD

**Issue by rodo** [theory/tap-parser-sourcehandler-pgtap#12]
If the PR https://github.com/theory/tap-parser-sourcehandler-pgtap/pull/11 is accepted, I'll do a similar PR to support own types détection.
Look forward for any advice on my first PR to do a better one on types

**Comment by theory** [comment]
Types detection? What kind?

**Comment by rodo** [comment]
For example if you defined an enum type as `CREATE TYPE carcolor AS ENUM ('red','blue');` you want to be sure the type will exists.

**Comment by theory** [comment]
Oh, you mean testing, not detection. Sorry. Sounds good!
