### ISSUE TITLE
Substitute environment variables used as options

### ISSUE THREAD

**Issue by ylavoie** [theory/tap-parser-sourcehandler-pgtap#15]
Environment variables should be useable as parameters for options.
Example:
EXPORT my_database=TEST
    prove --source Perl
          --ext=.t --ext=.pg
          --source pgTAP   --pgtap-option dbname=${my_database}
                           --pgtap-option username=postgres
                           --pgtap-option suffix=.pg

**Comment by rodo** [comment]
pgtap will use libpq to connect so you can already use the var defined by default, more documentation at https://www.postgresql.org/docs/current/static/libpq-envars.html
