### ISSUE TITLE
PostgreSQL v11 breaks pg_tapgen's _hasc() function

### ISSUE THREAD

**Issue by KiriakosGeorgiou** [theory/tap-parser-sourcehandler-pgtap#19]
In PostgreSQL v11 pg_class no longer has relhaspkey, so the query the _hasc() function runs is broken.  Also, per Tom Lane using relhaspkey in this way is incorrect.  I'll submit a pull request fixing this.

**Comment by tomascassidy** [comment]
@theory Will there be a new release coming soon for this fix?  I've just discovered pgtap and would love to try it out on PostgreSQL 11.

**Comment by theory** [comment]
[v1.0.0](https://pgxn.org/dist/pgtap/1.0.0) dropped a few days ago.

**Comment by tomascassidy** [comment]
Thanks.  I will wait for it to appear on apt.postgresql.org before I can test it out.  Does that happen automatically, or do I need to submit an issue somewhere else for that?

**Comment by theory** [comment]
I don't think its automatic. I don't know where the source list hosted, and a quick search didn't turn it up. :-( Suggest you ask in a community forum like IRC or the pgsql-general mail list ([subscription instructions](https://www.postgresql.org/list/pgsql-general/)).

**Comment by tomascassidy** [comment]
I checked the documentation at https://wiki.postgresql.org/wiki/Apt and it looks like the maintainers live on the pgsql-pkg-debian list at https://www.postgresql.org/list/pgsql-pkg-debian/.

Checking the list archives, it looks like you can just announce the new version on there with a pointer to the release on github and one of the maintainers there will do the update.

**Comment by theory** [comment]
Bah, sorry, it was pgTAP that was released, not pg_prove. I'll try to find some tuits to make a release in the next few days.

**Comment by theory** [comment]
I've released [v3.35 to CPAN](https://metacpan.org/release/DWHEELER/TAP-Parser-SourceHandler-pgTAP-3.35). Someone will have to nag the Postgres apt maintainers to update their package.

**Comment by tomascassidy** [comment]
https://redmine.postgresql.org/issues/4044

https://redmine.postgresql.org/issues/4045
