### ISSUE TITLE
Function MD5 tests are broken when extension types are in use

### ISSUE THREAD

**Issue by deathwish** [theory/tap-parser-sourcehandler-pgtap#21]
Introduced in #17, this is because generated tests look up function body by signature, and do so using the raw argument OIDs. While type OIDs are consistent for built-in primitives, this is not true for those provided by extensions, causing tests to only work on the generating machine.

Even worse, this does not produce a test failure, instead a plan failure is raised as no body with the given parameters is found, and thus no assertion is run.

To reproduce: Create a function with an hstore parameter and generate tests. Load this function on another machine and run the tests. Expected: success. Actual: fails.

Recommend disabling this functionality until fully baked. I'm willing and able to do a PR to make it actually work, but it may be a month or two before I have time.

**Comment by theory** [comment]
I believe this is fixed by #34 — thanks for the effort there!

**Comment by deathwish** [comment]
Glad I could help out, we have gotten a lot of use out of the project over the years!
