### ISSUE TITLE
pg_prove --color doesn't always output colors

### ISSUE THREAD

**Issue by dorian-marchal** [theory/tap-parser-sourcehandler-pgtap#23]
When I pipe `pg_prove` (for example in `cat`), colors are stripped.

I expected the `--color` flag to force color output (in the same way as `ls --color | cat`, for example).

Is there a way to force `pg_prove` to ouput colors?

My use case is executing `pg_prove` from node:

```shell
# Output color:
pg_prove --color /etc/passwd

# Doesn't output color:
pg_prove --color /etc/passwd | cat

# Doesn't output color:
node -e 'require("child_process").exec("pg_prove --color /etc/passwd", (err, res) => console.log(res));'
```

**Comment by theory** [comment]
pg_prove relies on App::Prove for this, and [it looks like it should force it if you specify it](/Perl-Toolchain-Gang/Test-Harness/blob/94e8ba4c942a0f4e4eb0a483a8a8c3ee9bd9ff61/lib/App/Prove.pm#L294-L296)
