### ISSUE TITLE
create a docker container for easier use of pg_prove in CI environments that support it

### ISSUE THREAD

**Issue by xenoterracide** [theory/tap-parser-sourcehandler-pgtap#30]
I have this https://github.com/xenoterracide/postgis-pgtap/blob/master/pgprove/Dockerfile happy to contribute under whatever license you desire. I could also work on one based on the `perl` image if that's desired.

this container supports `pg_tapgen` but we could go even lighter than that, and only support `pg_prove`

**Comment by theory** [comment]
I think the [existing Dockerfile](dist/Dockerfile) covers is, as well as [the released image](https://hub.docker.com/r/itheory/pg_prove), no?
