### ISSUE TITLE
Not a SCALAR reference at /usr/local/share/perl5/site_perl/TAP/Parser/SourceHandler/pgTAP.pm line 209

### ISSUE THREAD

**Issue by xenoterracide** [theory/tap-parser-sourcehandler-pgtap#31]
I know this description is probably not very useful, I haven't investigated it further yet... maybe it's meaningful to you though, or maybe there's another check that could be added...
``` Run docker run -v $PWD/src/test/resources/pgtap/test/script:/t -e "PGPASSWORD=$PGPASSWORD" \
  docker run -v $PWD/src/test/resources/pgtap/test/script:/t -e "PGPASSWORD=$PGPASSWORD" \
    --network=host xenoterracide/pg_prove:latest \
    pg_prove -e"TERM=xterm-256color" --host localhost --dbname briggo_production --username postgres --ext .sql --recurse --color /t
  shell: /bin/bash -e {0}
  env:
    PGPASSWORD: DontUseThisPassword
Not a SCALAR reference at /usr/local/share/perl5/site_perl/TAP/Parser/SourceHandler/pgTAP.pm line 209.
##[error]Process completed with exit code 255.
```

**Comment by theory** [comment]
It means that it has read the source of your test into memory, but not stored it as a scalar reference. No other value should be passed to it. I can add some code to detect if it's not an expected reference, but would have no idea how it got that way.

**Comment by theory** [comment]
Actually [the docs say](/theory/tap-parser-sourcehandler-pgtap/blob/1a6f207dd4b4fb7d46c4372d19041deae98db8a3/lib/TAP/Parser/SourceHandler/pgTAP.pm#L240-L242) what it's allowed to be. Maybe it's finding something weird because you're searching `/`? Likely to be a lot of crap included that you don't want, like `/dev/null`.
